language: python

python:
  - "3.8"

script:
  - sudo apt-get update
deploy:
- provider: elasticbeanstalk
  access_key_id: "AKIAYRN3MPKWW5WOJSZZ"
  secret_access_key: "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"
  region: "us-west-2"
  app: "mysite-2"
  env: "mysite2-env"
  bucket_name: "elasticbeanstalk-us-west-2-587192892077"
  on:
    branch: main
  skip_cleanup: true
