language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python3 manage.py migrate
  - python3 manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=polls manage.py test

after_script:
  - coveralls
